version: '3'
services:
  geo-worker:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - rq
      - worker
      - -u
      - redis://redis
    depends_on:
      - redis
  geo-rest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
  redis:
    image: redis
